import { RoomType, UserType } from '@/interface/nextBnb'

export const userMockData: UserType = {
  id: 1,
  email: 'alice@example.com',
  name: 'Alice Kim',
  image: '',
  desc: '여행을 좋아하는 프론트엔드 개발자입니다.',
  address: '서울특별시 마포구 홍익로 23',
  phone: '010-1234-5678',
  accounts: [
    {
      id: 'google-123',
      provider: 'google',
    },
  ],
  rooms: [
    {
      id: 101,
      images: ['https://example.com/room1.jpg'],
      imageKeys: ['room1.jpg'],
      title: '한강뷰 아파트',
      address: '서울특별시 용산구 이촌로 45',
      desc: '한강이 보이는 고급 아파트입니다.',
      bedroomDesc: '침실 2개, 욕실 1개',
      price: 120000,
      category: 'apartment',
      lat: '37.5300',
      lng: '126.9800',
      userId: 1,
      freeCancel: true,
      selfCheckIn: true,
      officeSpace: true,
      hasMountainView: false,
      hasShampoo: true,
      hasFreeLaundry: true,
      hasAirConditioner: true,
      hasWifi: true,
      hasBarbeque: false,
      hasFreeParking: true,
      createdAt: '2025-07-01T10:00:00Z',
      updatedAt: '2025-07-25T10:00:00Z',
      likes: [],
      comments: [],
      bookings: [],
    },
  ],
  // comments: [
  //   {
  //     id: 301,
  //     createdAt: '2025-07-20T09:30:00Z',
  //     roomId: 101,
  //     userId: '1',
  //     body: '정말 멋진 숙소였어요!',
  //     room: {
  //       id: 101,
  //       images: ['https://example.com/room1.jpg'],
  //       imageKeys: ['room1.jpg'],
  //       title: '한강뷰 아파트',
  //       address: '서울특별시 용산구 이촌로 45',
  //       price: 120000,
  //       category: 'apartment',
  //       lat: '37.5300',
  //       lng: '126.9800',
  //       freeCancel: true,
  //       selfCheckIn: true,
  //       officeSpace: true,
  //       hasMountainView: false,
  //       hasShampoo: true,
  //       hasFreeLaundry: true,
  //       hasAirConditioner: true,
  //       hasWifi: true,
  //       hasBarbeque: false,
  //       hasFreeParking: true,
  //       userId: 1,
  //     },
  //     user: {
  //       id: 1,
  //       email: 'alice@example.com',
  //       name: 'Alice Kim',
  //       accounts: [],
  //     },
  //   },
  // ],
  bookings: [
    {
      id: 401,
      roomId: 101,
      userId: '1',
      checkIn: '2025-08-01',
      checkOut: '2025-08-05',
      guestCount: 2,
      totalAmount: 480000,
      totalDays: 4,
      status: 'SUCCESS',
      createAt: '2025-07-15T14:00:00Z',
      updatedAt: '2025-07-15T14:00:00Z',
      room: {
        id: 101,
        images: ['https://example.com/room1.jpg'],
        title: '한강뷰 아파트',
        address: '서울특별시 용산구 이촌로 45',
        price: 120000,
        category: 'apartment',
        lat: '37.5300',
        lng: '126.9800',
        freeCancel: true,
        selfCheckIn: true,
        officeSpace: true,
        hasMountainView: false,
        hasShampoo: true,
        hasFreeLaundry: true,
        hasAirConditioner: true,
        hasWifi: true,
        hasBarbeque: false,
        hasFreeParking: true,
        userId: 1,
      },
      user: {
        id: 1,
        email: 'alice@example.com',
        name: 'Alice Kim',
        accounts: [],
      },
      payments: [
        {
          id: 'pay_001',
          paymentKey: 'kakaopay-1234',
          bookingId: '401',
          amount: 480000,
          status: 'DONE',
          orderId: 'ORD-20250715-0001',
          orderName: '한강뷰 아파트 예약',
          approvedAt: '2025-07-15T14:01:00Z',
          receiptUrl: 'https://example.com/receipt/pay_001',
          cardNumber: '1234-****-****-5678',
          method: 'CARD',
        },
      ],
    },
  ],
}

export const roomsMockData: RoomType = {
  id: 1,
  images: ['https://picsum.photos/800/600'],
  title: '도심 속 감성 가득한 아파트',
  address: '서울특별시 마포구 연남동',
  desc: '감성적인 인테리어의 아늑한 도심 속 숙소입니다.',
  bedroomDesc: '침실 1개 · 퀸 사이즈 침대 1개 · 최대 2인 숙박 가능',
  price: 85000,
  category: '아파트',
  lat: '37.5665',
  lng: '126.9780',
  freeCancel: false,
  selfCheckIn: true,
  officeSpace: true,
  hasMountainView: false,
  hasShampoo: true,
  hasFreeLaundry: true,
  hasAirConditioner: true,
  hasWifi: true,
  hasBarbeque: false,
  hasFreeParking: false,
  createdAt: '2025-07-20T14:30:00.000Z',
  updatedAt: '2025-07-27T08:15:00.000Z',
}
